branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: greenboard-env
  branch: null
  default_platform: PHP 7.0
  default_region: us-west-2
  profile: Brian
  repository: null
